studiopress/atomic-blocks

- src/blocks/block-accordion/index.js
Displaying markup only when a value exists means the 'edit:' and 'save:' outputs don't match if one of the values is empty. Causing a block error.
```
Expected:
<div class="wp-block-atomic-blocks-ab-accordion ab-block-accordion ab-font-size-18">
<details>
<summary class="ab-accordion-title">
<p>Title</p>
</summary>
<p class="ab-accordion-text"></p>
</details>
</div>
Actual:
<div class="wp-block-atomic-blocks-ab-accordion ab-block-accordion ab-font-size-18">
<details>
<summary class="ab-accordion-title">
<p>Title</p>
</summary>
</details>
</div>
```
> Edit and save don't match if attribute is empty

- dist/getting-started/getting-started.php
Fix uses correct path /assets (instead of not existing /inc) to enqueue Fontawesome.
> Fix for error enqueing Fontawesome

- src/blocks/block-accordion/index.js
- src/blocks/block-author-profile/index.js
- src/blocks/block-button/index.js
- src/blocks/block-container/index.js
- src/blocks/block-cta/index.js
- src/blocks/block-drop-cap/index.js
- src/blocks/block-notice/index.js
- src/blocks/block-post-grid/index.js
- src/blocks/block-post-grid/index.php
- src/blocks/block-sharing/index.js
- src/blocks/block-spacer/index.js
- src/blocks/block-testimonial/index.js
The POT file will need to be regenerated, but I'm not sure if the tools for that scan JS files yet.
Sorry about the large PR. My editor automatically strips unnecessary trailing whitespace for standards compliance.
> Add textdomain to translatable strings in block files.

- src/blocks/block-sharing/index.php
This fix checks for block attributes before outputting the corresponding class on the block.
> Check for attributes before outputting

- dist/getting-started/getting-started.css
Admin notices were showing up in the .ab-block-split-left div.
> Remove WP Forms notice from GS content area

- dist/assets/js/newsletter-block-functions.js
- dist/init.php
- includes/newsletter/newsletter-functions.php
- package-lock.json
- package.json
- src/blocks/block-newsletter/index.php
- src/blocks/block-pricing-table-inner/components/price/deprecated/deprecated.js
- src/blocks/block-pricing-table-inner/components/price/index.js
- src/blocks/block-sharing/index.php
This PR address the AMP compatibility issues in the pricing, sharing, notice, and newsletter blocks.
**General testing**
Be sure to have pages with these blocks already configured before checking out this branch. This will be useful for testing for regressions and for testing the pricing table deprecation.
Run `npm run build-assets` after checking out this branch.
**Pricing**
The block was outputting a `<span placeholder="$">` element on the front end, which AMP flags as an issue. This PR deprecates the save routine and removes the placeholder from the span. To test this, be sure you have an existing pricing table page before running this branch. Then check out this branch, build the assets, and edit the pricing table page, and update the post. This should remove any AMP warnings related …
> Updates for basic AMP compatibility

- src/blocks/block-post-grid/components/edit.js
- src/blocks/block-post-grid/components/inspector.js
Adjusts method of fetching and saving categories in the inspector.
This needs to be tested against WP 5.1.x and 5.2 to make sure it works as expected.
Closes #122.
> Use different method for fetching and saving categories in Post and Page Grid block. #122

- src/blocks/block-notice/components/button.js
- src/blocks/block-notice/components/inspector.js
- src/blocks/block-notice/index.js
Fixes #118, where dismiss icon was showing no matter what option was selected.
This PR also includes fixes to remove unused components and functions throughout the block.
> Notice block: Fix bug in Notice Display setting.

- dist/assets/js/dismiss.js
In `dismiss.js`:
- Removes ES6 syntax
- Removes jQuery dependency
Closes #125.
> Remove ES6 syntax and jQuery dependency in dismiss.js #125

- src/blocks/block-column-inner/deprecated/1.7.1/components/column.js
- src/blocks/block-column-inner/deprecated/1.7.1/components/save.js
- src/blocks/block-column-inner/deprecated/deprecated.js
- src/blocks/block-column-inner/index.js
- Deprecate old container save and column component
- Add this.props.className output
Fixes #119.
This block required a deprecation, so we'll want to test a few different instances. Here's a quick reminder about how to test deprecations. 
- Switch to the master branch and create a test block
- Save the page
- Switch to the fix branch and regenerate assets with `npm run build-assets`
- Reload the page and check the status of the block 
In this deprecation, we added the `className` output to the block, so you should now see the Additional CSS Class output on each individual column. The block should also pass the content comparison and return without any invalid content warnings that break the block.
> Add className output to inner container on Advanced Columns

- src/blocks/block-sharing/components/edit.js
- src/blocks/block-sharing/components/inspector.js
- src/blocks/block-sharing/index.php
Google shut down Google+, so we can remove this option.
**Fixes:** #85 
Remove Google+ option from Sharing block.
> Remove Google+ option from Sharing block. #85

- src/blocks/block-accordion/components/accordion.js
- src/blocks/block-accordion/index.js
By removing the default value, users can clear the font size output and use their theme font sizes instead.
- Set default value on attribute to null
- Added check for font value before outputting class
Does not apply
1. Check out the 2.0 branch
2. Add an accordion block to the page, set a font size, save the page
3. Switch to issue/171 branch
4. Refresh the page, clear the default font value from the slider, and save the page
5. Check to make sure the block doesn't break and that a font class wasn't output on the front end
**Fixes:** #171
> Remove default font value

- src/blocks/block-accordion/components/inspector.js
- src/blocks/block-accordion/styles/style.scss
- src/blocks/global-styles/styles/style.scss
- Make font size adjustment specific to accordion title so child blocks can control their own font.
- Move the accordion font size selector to the accordion stylesheet.
Change the font size adjustment on the accordion and ensure child blocks don't get these font styles applied.
**Fixes:** #177
> Remove overly specific font size styles

- dist/assets/js/newsletter-block-functions.js
- includes/classes/class-mailchimp.php
- includes/newsletter/newsletter-functions.php
- src/blocks/block-newsletter/components/inspector.js
- src/blocks/block-newsletter/index.php
- src/blocks/block-newsletter/styles/editor.scss
Adds an option to the newsletter block called `Enable Double Opt-In`, which will add the member to the list in a pending status and trigger a confirmation email from Mailchimp.
- Check out `issue/143`
- Run `npm run build-assets`
- Add block to page
- Select desired list
- Enable Double Opt-In option
- Publish page
- Subscribe to list
- Confirm that you get a double opt-in confirmation email from Mailchimp
- Disable Double Opt-In option
- Save page
- Subscribe to list
- Confirm that you do not get a double opt-in email and that your email was automatically subscribed to the selected list.
**Fixes:** #143 
Added Double Opt-In support to newsletter block.
> Add double opt-in option to newsletter block. #143

- src/blocks/block-author-profile/styles/editor.scss
- src/blocks/block-author-profile/styles/style.scss
- src/blocks/global-styles/styles/editor.scss
Fixes #184.
Make image hover CSS more specific and relocate to better spot.
Add a testimonial and author profile block with an avatar on each. The image opacity should fade slightly on hover. 
**See:** #xxx
**Fixes:** #184 
Improve image hover styles on author profile and testimonial block.
> Improve image hover styles

- src/blocks/block-column-inner/styles/editor.scss
This needed a few additional selectors to take into account other use cases. Fixes #188.
> Refine sibling selector for one column

- src/blocks/block-column-inner/styles/editor.scss
This `display: block` is causing issues with core image alignment. We can safely remove this. 
Add an image to a post, you should be able to left, center, and right align the image.
**Fixes:** #193
> Fix display block alignment

- config/webpack.config.dev.js
- config/webpack.config.prod.js
Remove CSS Grid autoprefixer support in favor of our own styles.
Run a build and ensure the autoprefixer isn't outputting MS specific styles.
**Fixes:** #204
> Remove CSS Grid autoprefixer support

- src/blocks/block-column-inner/styles/style.scss
- src/utils/components/background-image/classes.js
This PR fixes #212, removing a wildcard selector that applies relative positioning to all child elements.
> Remove wildcard selector for column styles

- dist/init.php
Removes the jQuery dependency loading by dismiss.js, since that code no longer requires jQuery.
- In the latest release or master version of AB, note that jQuery is loaded on the front end.
- Check out `issue/210`
- Unless the theme or another plugin requires jQuery, it should no longer be loaded on the front end.
- Verify that Notice dismissals work as expected. Three things:
- Dismissible notices are dismissed when you click the X to dismiss them
- Dismissible notices do not show again when you refresh the page after dismissing them
- Non-dismissible notices still show as they did before
**Fixes:** #210 
Removed unnecessary jQuery dependency in Notice block.
> Remove jQuery from dependency array on dismiss.js. #210

- src/blocks/block-column-inner/index.js
Copied from https://github.com/studiopress/atomic-blocks/pull/203, originally opened by @nickcernis.
Fixes https://github.com/studiopress/atomic-blocks/issues/202 for WP 5.0 (without affecting WP 5.2).
Not required.
1. `git checkout fix/column-vertical-alignment`
2. `npm ci` if deps are not yet installed.
3. `npm run build`
4. Under WP 5.0: visit `/wp-admin/post-new.php?post_type=page` with Atomic Blocks active.
5. Click in the main editor section. You should no longer see the block editor crash.
6. Create an AB Advanced Columns block and set the vertical alignment.
7. Confirm the vertical alignment class is added to the columns block on the front and back end (e.g. …
> Fix editor crash under WP 5.0

- src/utils/components/background-image/classes.js
Small fix to the background image opacity slider. 
To test, add the column block, set a background image, take the slider down to zero. The background image should disappear. 
Fixes #218
> Fix background image opacity on column block

- src/blocks/block-post-grid/components/inspector.js
- src/blocks/block-post-grid/index.php
- src/blocks/block-post-grid/styles/style.scss
- Change the column slider minimum to 1
- Add styles for 1 column layout
- Check out the branch
- Run `npm run start` to rebuild the assets
- Add the Post Grid to the page and change the column slider to 1
**Fixes:** #223 
Add one column support to the Post Grid block.
> Add one column support to the Post Grid block

- src/blocks/block-layout/components/layout/layout-modal.js
Sets the `modalOpen` state value in `componentDidMount`, which fixes the issue described in #226.
- Using latest version of AB, download latest version of Gutenberg plugin.
- Note that the modal does not open when layouts are added to the page.
- Check out this branch, run `npm run start` to build the assets.
- Repeat test above and verify that modal opens.
- Verify this still works as expected without Gutenberg plugin active.
**Fixes:** #226.
> Set modal state in componentDidMount. #226

- dist/getting-started/getting-started.php
Removes the sidebar that talks about the Gutenberg plugin and no longer automatically activates the plugin if it's installed but deactivated.
Related content pulled in from atomicblocks.com feed has been updated to remove links to Gutenberg plugin.
Fixes: #221.
> Do not automatically activate the Gutenberg plugin. #221.

- includes/classes/class-mailchimp.php
Increasing number of lists retrieved from MailChimp API to 200, up from the default of 10.
Note: Requires a MailChimp account with more than 10 lists.
- Check out the `issue/224` branch here.
- Using the [Transients Manager plugin](https://wordpress.org/plugins/transients-manager/), clear the `atomic_blocks_mailchimp_lists` transient on your site.
- Add the newsletter block to a new page.
- Ensure that more than 10 lists are returned in the dropdown in the sidebar.
**Fixes:** #224.
Newsletter block: Fixes mailing list dropdown issue on MailChimp accounts with more than 10 mailing lists.
> Increase number of mailing lists retrieved. #224

- src/blocks/block-column-inner/styles/style.scss
Fix Grid styles in IE11 by adding a `-ms` fallback prefix.
Good luck! 
**See:** #241 
**Fixes:** #241 
Improve Grid styles in IE11.
> Fix Grid styles in IE11

- includes/layout/layout-endpoints.php
- src/blocks/block-layout/components/edit.js
- src/blocks/block-layout/components/layout/layout-library-item-card.js
- src/blocks/block-layout/components/layout/layout-library-item-list.js
- src/blocks/block-layout/components/layout/layout-library-item.js
- src/blocks/block-layout/components/layout/layout-library.js
- src/blocks/block-layout/components/layout/layout-modal.js
- src/blocks/block-layout/components/layouts-provider.js
- src/blocks/block-layout/styles/editor.scss
- Adds support for additional layouts via `atomic_blocks_additional_layout_components` filter.
- Adds additional Reusable Blocks tab to modal.
- Adds support for additional layouts via `atomic_blocks_additional_layout_components` filter.
> Add support for additional layouts to layout library

- includes/layout/class-component-registry.php
- includes/layout/layout-functions.php
Adds `AtomicBlocks\Layouts\Component_Registry\remove()` method to allow for unregistering layouts.
Adds `atomic_blocks_unregister_layout_component()` helper function that uses aforementioned method to unregister layout components.
Not yet.
Add the following code to a custom plugin and ensure the Business layout is removed.
```
add_action( 'plugins_loaded', function() {
atomic_blocks_unregister_layout_component( 'layout', 'ab_layout_business_1' );
}, 12 );
```
**Closes:** #255
> Add ability to unregister layout components. #255

- phpcs.xml.dist
- src/blocks/block-newsletter/index.php
This PR removes the JS code from the submit process of the Newsletter block when the plugin `leadin` (HubSpot) is activated. It also adds a rule to ignore Short Array Syntax.
> Allow HubSpot to capture Newsletter emails

- src/blocks/block-newsletter/index.php
Fix issue with `is_plugin_active` not being available. Introduced in https://github.com/studiopress/atomic-blocks/pull/267.
> Change way we detect HubSpot plugin

- dist/getting-started/pages/settings-general.php
Add a class to style the description text under the Mailchimp setting.
Visit the settings page and check the class on the Mailchimp setting.
Add a class to style the description text under the Mailchimp setting.
> Add class to setting description text

- atomicblocks.php
- src/blocks/block-container/index.php
**Summary of change:** 
Fix container block background image to be object-fit:contain in AMP pages.
Does not apply
1. Set up a site with https://wordpress.org/plugins/amp/
2. Set AMP website template mode to Transitional
3. Insert a container block and choose a background image.
4. View non-AMP post on frontend and take note of background.
5. Now view AMP version and see the image doesn't cover the container.
With the changes in this PR, the AMP and non-AMP version now appear the same. This is accomplished by injecting AMP's `object-fit="contain"` attribute onto the underlying background `img`, this has the effect of overriding the default `object-fit:contain` added to intrinsic-layout …
> Ensure object-fit:cover applies to image in container block

- dist/getting-started/getting-started.php
- dist/init.php
**Summary of change:** 
The Font Awesome stylesheet is large and if it is not needed on the page then it wastes bandwidth and browser CPU cycles. It also contributes negatively to the overall CSS budget of 50KB on AMP pages (see https://github.com/ampproject/amp-wp/issues/4095). Therefore, the stylesheet should only be printed when it is actually needed by a block.
This has the added benefit of preventing the Font Awesome stylesheet from blocking the rendering content that appears before the first block that makes use of it.
This PR also centralizes the registration of the Font Awesome stylesheet in the `wp_default_styles` action, eliminating duplicated references to the stylesheet path.
Does not apply
**How …
> Register Font Awesome stylesheet once and print only when needed

- src/blocks/block-column-inner/styles/editor.scss
- src/blocks/block-column-inner/styles/style.scss
- src/blocks/block-layout/styles/editor.scss
- src/blocks/block-post-grid/styles/style.scss
- src/blocks/block-pricing-table-inner/styles/editor.scss
- src/blocks/block-pricing-table-inner/styles/style.scss
Add missing IE11 prefixes for CSS Grid in Columns block.
Create a few different column layouts and visit them in IE11. Columns should behave as expected.
**Fixes:** #257 
Improve CSS Grid styles for Advanced Column block in IE11.
> Add missing IE prefixes for CSS Grid

- src/blocks/block-post-grid/index.php
Check if post grid image is available before outputting. 
See ticket #289 for circumstances where you will see this issue. 
**Fixes:** #289 
Fix error notice for missing thumbnails in PHP 7.4.
> Check if featured image is available before attempting to output one.

- dist/init.php
Fixes the issue noted in #127 and introduced in #294, where icons in existing AB Sharing blocks will fail to load in the editor if REST requests return rendered page content that contains an AB Sharing block.
No docs required.
1. Add an AB Sharing block to a new page.
2. Confirm that:
Fix an issue where AB Sharing block icons could fail to load in the editor.
**Notes:**
This is branched from master and targets master since it's a patch. Happy to rebase on develop if needed, though.
> Do not attempt to inline Font Awesome CSS in the editor

- src/blocks/block-column-inner/styles/editor.scss
Users reported that columns and container did not work in latest Gutenberg 7.4.0 release. This is because the plugin has introduced new `block-` prefixes on markup in the editor. Until this change is merged into core, we'll have to maintain both styles to accommodate users who are using the plugin.
I did not find any issues with the container block, nor does it contain any particular editor styles that should conflict.
1. Switch to `master` and activate the latest Gutenberg plugin.
2. Create a 3 column layout in a page.
3. Observe the stacked columns.
4. Pull down `issue/298` and run the build. 
5. Check to see if the columns are fixed.
**See:** #298 
**Fixes:** #298 
Improve styles for users who are experimenting with …
> Improve column styles for Gutenberg plugin

- composer.json
- includes/layout/layout-endpoints.php
- src/blocks/block-layout/components/layouts-provider.js
- tests/integration/layout-endpoints/test-layout-endpoints.php
- Adds `atomic_blocks_allowed_layout_components` filter for controlling layouts shown in the modal.
- Adds `filter=allowed` param to All Layouts endpoint. Follows WPE standard for filtering endpoint data in HTTP APIs.
- Updates phpcs command line options in composer.json for better coverage and easier maintenance.
- Adds test coverage for new filtering feature, and some additional coverage for existing functionality.
- Check out `allowed/layouts` branch, run `npm run start`, and ensure nothing is broken.
- Test filtering the allowed layouts and ensure only the ones you allowed are shown in the modal. Example filter to get you started:
```
add_filter( 'atomic_blocks_allowed_layout_components', function( $layouts ) {
return ['ab_layout_hero_1', …
```
> Add support for filtering allowed sections and layouts.

- dist/getting-started/getting-started.php
- dist/init.php
This reverts commit 0ab51fcdfe7e3265b832f7f5cf8efc0ec8a36a8c, reversing
changes made to b336ce3ff6fad3cc979ba27ed228545dbeb48687.
We've had a number of reports that front-end styles aren't loading. One common factor is Polylang is loaded on these sites, with the "URL modifications" setting enabled. When this setting is enabled, the function hooked on wp_default_styles doesn't seem to run properly. 
Additionally, we've had a report of our CSS file overriding another Font Awesome plugin. See https://wordpress.org/support/topic/atomic-blocks-overriding-font-awesome-5-pro-kit-in-css/
In the interim, I think we should revert this until we have time to dig in a little deeper.
**Original issue and PR**
Issue #127. PR #294.
See also #308.
> Revert PR for just-in-time loading for Font Awesome and the main plugin styles

- src/blocks/block-post-grid/styles/style.scss
Add the missing comma to post grid styles.
Check out the branch, add the post grid block, and try to create a four column layout. You should get a proper four column layout.
**See:** #313 
**Fixes:** #313 
Fix four column layout styles in Post Grid block.
> Add missing comma in post grid styles

- dist/getting-started/getting-started.php
> Clear MailChimp list cache when saving settings. #250

- atomicblocks.php
- loader.php
Closes #330.
To test this, do the following:
- Install latest AB Pro beta
- Clone this branch into wp-content/plugins/atomic-blocks, but leave the plugin deactivated.
- Install a Genesis OCTS theme, like Essence Pro.
- Go to Appearance > Child Theme Setup and click "Set up your website" button.
These steps mimic what Genesis would do if this fix were already deployed to wp.org. When Genesis instructs WP to activate the code in this branch, you should not see any fatal errors and the OCTS process should complete like normal.
See the comment in the main `atomicblocks.php` file for more info. Nearly all the logic that lived in the main plugin file now lives in `loader.php` and was not changed.
> Tweak plugin loader code to avoid possible PHP fatal errors under certain conditions.

- dist/getting-started/pages/settings-general.php
- dist/getting-started/pages/settings-main.php
- dist/getting-started/settings.js
This improves the logic of the settings display so that settings on the General tab do not mistakenly show up on another tab. This gives us a quick fix until we can revisit the whole settings architecture later.
> Adjust logic of settings display

- package.json
- src/blocks/block-post-grid/components/edit.js
- src/blocks/block-post-grid/components/inspector.js
- src/blocks/block-post-grid/index.php
- src/blocks/block-post-grid/styles/editor.scss
Add option to select pages in the post/page grid.
1. Run `npm install` to grab the react-select package and dependencies. 
2. Compile the blocks.
3. Add the Post/Page Grid block and select the Page post type. 
4. Select pages using the select menu and test.
- Add the option to select specific pages in the page grid.
- This draft PR just covers the editor view.
- When script debug is on, react-select throws a few strict warnings. Discussion about them are happening [here](https://github.com/JedWatson/react-select/issues/3751) and [here](https://github.com/JedWatson/react-select/pull/3928). I've confirmed the latter PR fixes one of the warnings.
> Add page select feature to post grid

- src/blocks/block-column-inner/styles/editor.scss
- src/blocks/block-container/styles/editor.scss
- src/blocks/block-pricing-table-inner/styles/editor.scss
Remove the cascading padding and only apply to top level containers to bring controls into view.
1. Add a container block, make it full width, add content to it. Ensure that the left/right padding is only applied to the top level container, and doesn't cascade down to the blocks within. 
2. Test against container, columns, and pricing table.
- Improve editor padding on nested blocks.
> Improve editor padding

- src/blocks/block-notice/styles/style.scss
Defer to the theme styling instead of resetting color. This was brought up in the AB help channel in WPE Slack.
1. Activate a Genesis theme, go to Appearance -> Customize -> Colors and select a link color.
2. Add a notice block and add a link in the content area. 
3. Confirm the link color matches the color you set in the customizer.
- Defer link style in Notice block to theme link styling.
> Fix notice link style

- package-lock.json
- package.json
Adds `css-loader` dependency, which is required to build the CSS assets included in JS. I ran into an issue while testing Circle CI stuff with this missing dependency.
To test:
- Check out the `develop` branch, preferably in a new install.
- Run `npm install && npm run build-assets`. You should see errors here.
Then
- Check out `add/css-loader` branch
- Run `npm install && npm run build-assets`. You should see no errors.
> Add css-loader npm dep

- atomicblocks.php
This makes the file path to loader.php more explicit. This fixes an issue where, under certain conditions, the plugin's loader.php would not be loaded on the front end of the site.
Reported in support here: https://wordpress.org/support/topic/no-css-being-read-from-ab/
I tracked this down and tested the fix on the user's site to confirm.
> Be more specific about loader.php location

- src/blocks/block-post-grid/styles/editor.scss
Some old CSS was hiding the column setting when choosing pages in the Post/Page Grid. The solution also requires [a fix in Genesis Page Builder](https://github.com/studiopress/genesis-page-builder/pull/56).
Fixes #370 
1. Pull down branch and build assets. 
2. Grab the matching branch from GPB. 
3. Add the Post Grid block, change to Page type, and ensure the column setting is visible and working.
- Make column setting visible when working with pages in the Post and Page Grid block.
This PR has a matching [PR in Genesis Page Builder](https://github.com/studiopress/genesis-page-builder/pull/56).
> Show column setting when using Page Grid.

- src/blocks/block-layout/components/layout/layout-modal.js
Removes deprecated property to fix e2e failures per https://github.com/studiopress/atomic-blocks/pull/398#pullrequestreview-488765457
> Remove deprecated isLarge prop from Button

- dist/getting-started/getting-started.css
- dist/getting-started/getting-started.php
- dist/init.php
- src/blocks/block-layout/components/layout/layout-modal.js
- Updates admin sidebar menu label.
- Updates conditionals that gate CSS and JS loading on Getting Started Page.
- Updates the Getting Started page CSS to account for the new dynamic classes generated by WP because of the rename.
> Rename "Genesis Page Builder" to "Genesis Blocks Pro".

- src/blocks/block-column-inner/styles/editor.scss
- src/blocks/block-container/styles/editor.scss
- src/blocks/block-pricing-table-inner/styles/editor.scss
Ensures that full width container, pricing, and advanced column blocks do not have additional padding in the editor under WordPress 5.5.
Applies the same fix @dreamwhisper made to Genesis Blocks in https://github.com/studiopress/genesis-blocks/pull/45.
Fixes #395.
Under WP 5.5+.
1. Add a container, pricing, and advanced column block.
2. Set each to full-width.
3. In the editor, check that there is not excessive padding to the left and right of the blocks.
- Removed unnecessary padding in the editor on full-width Container, Pricing, and Advanced Column blocks.
> Fix full-width container editor padding in WP 5.5

- src/blocks/block-column-inner/components/edit.js
- src/blocks/block-column/components/edit.js
- src/blocks/block-pricing-table/index.js
Fixes https://github.com/studiopress/atomic-blocks/issues/397 for WP 5.5 so that:
- New columns in the advanced column block display placeholder text.
- Increasing the number of columns in the Advanced Columns and Pricing blocks shows new columns.
Applies the same fixes already tested and deployed in Genesis Blocks:
- https://github.com/studiopress/genesis-blocks/pull/51
- https://github.com/studiopress/genesis-blocks/pull/54
- https://github.com/studiopress/genesis-blocks/pull/55
Under WP 5.5+:
1. Add a pricing block with 2 columns.
2. Increase the column count to 3. You should see three columns.
3. Add an advanced columns block with 2 columns. You should see placeholder content for all columns.
4. Increase the column count to 3. You should see three columns with placeholder content in …
> Make column count work under WordPress 5.5

- src/blocks/block-post-grid/index.php
The previous logic checked to see if the manual excerpt was empty before
generating one automatically. The problem was when checking for a
manual excerpt, it passed the data through the `the_excerpt` filter.
In cases where themes or plugins filtered `the_excerpt`, this caused
our empty check to assume there was a manual excerpt, therefore no
automatic excerpt was generated. An example of where this can
happen is with social sharing plugins that use the filter to add
sharing links/buttons.
This changes the logic so that it passes the data through
`the_excerpt` later, which avoids this issue.
Additional changes:
* Only checks for excerpts when the block is configured to show them.
1. Check out `master` branch.
2. Configure the Post Grid block to show excerpts.
3. Be sure some posts have …
> Fixes issue where automatic excerpts are not displayed.

- dist/migration/admin.migration-notice.css
- dist/migration/admin.migration-notice.js
- dist/migration/class-notice.php
- loader.php
This PR adds an admin notice directing the user to migrate to Genesis Blocks. It also lets them click "Not Now" to dismiss it. 
This work mirrors most of what @kienstra did in Block Lab. 
It still needs the proper URL for the "Migrate" button. The work for that is outlined here:
https://wpengine.atlassian.net/browse/GF-2417
> Add Admin notice for migration. Includes not now option.

- dist/migration/migrate-page/ab-migrate.php
Feedback from @robstino and @lukecarbis at https://github.com/studiopress/genesis-blocks/pull/112#issuecomment-706780635 suggested updating the button label to make it more clear that GB will be installed _and activated_.
Tagging @susannelson for visibility because this has an impact on any screenshots taken so far.
> Use “Install and Activate Genesis Blocks” for button label to better set expectations

- dist/migration/class-notice.php
Updates migration notice logic to save the time the notice was dismissed and uses that time to determine when to display the notice again.
1. Dismiss notice.
2. Check user meta to ensure timestamp was saved to `atomic_blocks_show_migration_notice`.
3. Ensure the notice does not display again.
4. Adjust the timestamp saved in step 2 so that it reflects a timestamp that was 2 weeks or more in the past.
5. Ensure the notice displays again.
> Make migration notice reappear after 2 weeks. #411
