src/blocks/block-sharing/index.php
=> Rename array_social_icon_footer_script() to atomic_blocks_social_icon_footer_script(). #5

.gitignore, bin/phpcs-changed.sh, composer.json, phpcs.xml.dist
Adds phpcs dependencies via composer.
Adds a phpcs ruleset.
=> Add phpcs dependencies. #61

src/blocks/block-notice/components/inspector.js, src/blocks/block-notice/components/notice.js, src/blocks/block-notice/index.js, src/blocks/block-pricing-table-inner/components/inspector.js, src/blocks/block-spacer/components/inspector.js, src/blocks/block-testimonial/components/inspector.js
Move the <PanelColorSettings> out of <PanelBody> to fix the borked styles.
=> Move settings to fix styling

atomicblocks.php, dist/getting-started/getting-started.php, dist/init.php, src/blocks/block-sharing/index.php
=> Apply WP coding standards. #71

src/blocks/block-container/components/inspector.js
Increasing the max padding on the container for improved styling on SP homepages.
=> Increase padding max to 30

src/blocks/block-newsletter/index.php
=> Change input type to email

src/blocks/block-newsletter/index.php
=> Add className output to front end of newsletter

src/blocks/block-accordion/styles/style.scss
=> Remove accordion link styles. #84

src/blocks/block-post-grid/index.php
=> Fix excerpt length in post grid block. #83

src/blocks/block-author-profile/components/inspector.js
=> Add a description below the Email URL field. #51

atomicblocks.php
=> Do not redirect during plugin activation on multisite. #82

.circleci/config.yml, README.txt, composer.json, src/blocks/block-newsletter/index.php
This PR introduces CI using CircleCI tool. It would be creating an environment with composer, PHP 5.6, 7.1, 7.2 and 7.3, run tests (`composer phpunit`) and coding standards validation (`composer phpcs`).
=> Introducing CI with CircleCI

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json
=> Update autoprefixer and add grid support for IE. #89

dist/assets/js/newsletter-block-functions.js, src/blocks/block-newsletter/components/edit.js, src/blocks/block-newsletter/index.php
=> Add instance ID to input field. #106

src/blocks/block-post-grid/styles/style.scss
=> Improve grid support in post grid

src/blocks/block-post-grid/components/image.js
=> Update Learn More link to add aria-label and noreferrer noopener. #124

src/blocks/block-post-grid/components/edit.js, src/blocks/block-post-grid/index.js
=> Add full width alignment to post grid

src/blocks/block-author-profile/components/avatar.js, src/blocks/block-author-profile/components/edit.js, src/blocks/block-author-profile/components/inspector.js, src/blocks/block-author-profile/components/profile.js, src/blocks/block-author-profile/components/save.js, src/blocks/block-author-profile/deprecated/1.7.0/components/save.js, src/blocks/block-author-profile/deprecated/1.8.1/components/save.js, src/blocks/block-author-profile/deprecated/deprecated.js, src/blocks/block-author-profile/index.js, src/blocks/block-author-profile/styles/style.scss
This update address and fixes #139.
This block was deprecated to make these changes, so please test accordingly with the old block/new block.
=> Update Author Profile to use figure tag

README.md, README.txt, atomicblocks.php
Update readme to reflect changes in maintenance release.
=> Bump version, update changelog

README.txt
Adds a video embed of the layout block to the wp.org page.
=> Add layout video wporg page

src/blocks/block-column-inner/styles/editor.scss
Fixes #188.
Adds a `>` selector to specify column grid styles.
**Fixes:** #188 
Fix column grid specificity.
=> Fix column grid specificity

src/blocks/block-pricing-table-inner/styles/style.scss
Adds explicit placement support to grid columns for IE11.
Fixes #197.
=> Improve pricing table styles for IE11

README.md, README.txt, atomicblocks.php
Prepping for 2.0.2 release by bumping readme and updating the changelog.
=> Release 2.0.2

src/blocks/global-styles/styles/style.scss
Adding a div specifier to make the background styles more bulletproof. We can revisit this in the future to improve it further and maybe remove the specifier. For now, we can assume a div will be present.
=> Prefix background styles

src/blocks/block-layout/components/layout/layout-modal.js, src/blocks/block-layout/styles/editor.scss
Add a link to the feedback survey to the layout modal.
=> Add feedback link to modal

README.md, README.txt, atomicblocks.php, includes/layout/class-component-registry.php, languages/atomic-blocks.pot
Updates version number and readme.txt.
Needs:
- Verify change log.
- Run `npm run build` locally before deploy.
Closes #259.
=> Update version and changelog for 2.2.0

dist/getting-started/getting-started.php
Add a quick ABP check before outputting the ABP notice.
**Fixes:** #269
=> Add check for ABP in GS page

src/blocks/block-spacer/styles/style.scss
Remove the goofy 2020 styles from the spacer
=> Remove 2020 styles from spacer

src/blocks/global-styles/styles/style.scss
Fix column background color styles when used with an image.
Fixes #280
1. Check out branch, 
2. Add AB Columns to page
3. Add a background image with opacity and set the background color
4. Make sure you can see the background color showing through the image
**Fixes:** #280 
Fix column background color styles when used with an image.
=> Fix background color styles

src/blocks/block-post-grid/styles/style.scss
Add new prefix styles to accommodate class prefix in the future. This new prefix is used on the portfolio.
Check out branch, add the post grid, check the styles. There should be no visible change to the post grid. 
Improve class prefixes for post grid and portfolio styles.
=> Add ab- prefix to styles

src/blocks/block-newsletter/components/edit.js
Opens "Configure your settings" link in new tab.
Closes #290.
=> Open newsletter settings link in new tab. #290

src/blocks/block-spacer/components/inspector.js
Updates "Spacer Height" min value to 30 to match the default.
Closes #282
=> Change spacer height min to 30 to match default. #282

dist/assets/js/dismiss.js
=> Add Nodelist.forEach polyfill for IE11. #236

dist/getting-started/settings.js
Fixes settings visibility selectors.
=> Tweak selectors on settings tab UI

package-lock.json, webpack.config.js
Updates the webpack exclusions to an array of paths.
=> Change webpack config exclusions from regex to array of paths

atomicblocks.php, loader.php
=> BH-237: Move atomic_blocks_is_pro() function to loader.php.

dist/getting-started/getting-started.php, dist/getting-started/pages/gpb-getting-started.php
This touches a minimal amount of code, deferring further improvements to this mess for work planned in the future.
=> Updates the analytics opt-in option name to be in sync with GPB.

dist/getting-started/getting-started.css, dist/getting-started/pages/ab-getting-started.php
Fix the weird white box and tab toggles in Getting Started page.
1. Pull branch, check the GS pages in both AB and GPB.
=> Fix quirks in AB GS page.

src/blocks/block-column-inner/styles/editor.scss, src/blocks/global-styles/styles/editor.scss, src/blocks/global-styles/styles/style.scss, src/blocks/global-styles/styles/type.scss, src/blocks/global-styles/styles/utility.scss
Add supporting CSS enhancements for new sections and layouts.
- Improve display of nested columns
- Introduce utility classes to help with section and layout customization
- Introduce fluid title font
1. Pull down branch and rebuild assets. 
2. This will also require the new [layout branch](https://github.com/studiopress/genesis-page-builder/pull/43) from GP. 
- Add supporting CSS enhancements for new sections and layouts.
=> CSS fixes and enhancements
